version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/docker/volumes/pgdata
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=post-gres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=projectx
    restart: unless-stopped
# APP*****************************************
  springbootapp:
    image: project-x:latest
    network_mode: bridge
    container_name: project-x
    expose:
      - 8070
    ports:
      - 8070:8070
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: